[project]
name = "seapopym"
version = "0.1.0"
description = "Seapodym is a Python package that provides models to simulate the dynamics of low and mid trophic level marine ecosystems."
authors = [
    { name = "Jules Lehodey", email = "lehodey.jules+seapopym@gmail.com" }
]
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.12,<3.13"

dependencies = [
    "xarray>=2025.9.0",
    "dask>=2025.9.0",
    "distributed>=2025.9.0",
    "cf-xarray>=0.10.9",
    "pint>=0.25",
    "pint-xarray>=0.6.0",
    "numba>=0.61.2",
    "attrs>=25.3.0",
    "pyarrow>=21.0.0",
    "numpy>=1.24.0",
    "netcdf4>=1.6.0",
]

[project.urls]
repository = "https://github.com/SeapoPym/seapopym.git"
documentation = "https://seapopym.readthedocs.io/en/latest/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
